server:
  port: 8080
  servlet:
    context-path: /simple_web
spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./db/testDB
    url: jdbc:h2:tcp://localhost:9092/./db/testDB
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
#   trace debug info warn error fatal off
