CREATE TABLE SIMPLE_RANDOM.STATISTIC (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	PATH CHARACTER VARYING(500),
	CREATE_TIME TIMESTAMP DEFAULT LOCALTIMESTAMP,
	CONSTRAINT STATISTIC_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2A ON SIMPLE_RANDOM.STATISTIC (ID);